In [1]:
import numpy as np
import cv2

In [2]:
img = cv2.imread('./m1/flemingo.jpg')

In [3]:
print(img)
# most of images are 3d images

[[[151 130 115]
  [151 130 115]
  [151 130 115]
  ...
  [151 130 115]
  [151 130 115]
  [151 130 115]]

 [[151 130 115]
  [151 130 115]
  [151 130 115]
  ...
  [151 130 115]
  [151 130 115]
  [151 130 115]]

 [[151 130 115]
  [151 130 115]
  [151 130 115]
  ...
  [151 130 115]
  [151 130 115]
  [151 130 115]]

 ...

 [[120  94  77]
  [120  94  77]
  [120  94  77]
  ...
  [114  90  72]
  [114  90  72]
  [118  94  76]]

 [[120  94  77]
  [120  94  77]
  [120  94  77]
  ...
  [110  86  68]
  [110  86  68]
  [117  93  75]]

 [[120  94  77]
  [120  94  77]
  [120  94  77]
  ...
  [107  83  65]
  [107  83  65]
  [116  92  74]]]


In [4]:
img.shape
#3 = thre channel format(b,g,r), first two value represnet image pixel size

(254, 198, 3)

In [6]:
# display image 
cv2.imshow('example', img)
cv2.waitKey(10000) # wait time to display image for 
cv2.destroyAllWindows() # after 10k time counter destroy window

In [7]:
# display image unti any key press
cv2.imshow('example', img)
cv2.waitKey(0) # wait time to display image for 
cv2.destroyAllWindows() # after 10k time counter destroy window

In [8]:
# save image neer arry or big matrix 
cv2.imwrite('./m1/example.png',img)

True

In [9]:
cv2.imread('filename.jpg',0)

In [10]:
500*500

250000