In [2]:
import cv2
import numpy as np

In [3]:
img = cv2.imread('./m1/flemingo.jpg')

In [4]:
img

array([[[151, 130, 115],
        [151, 130, 115],
        [151, 130, 115],
        ...,
        [151, 130, 115],
        [151, 130, 115],
        [151, 130, 115]],

       [[151, 130, 115],
        [151, 130, 115],
        [151, 130, 115],
        ...,
        [151, 130, 115],
        [151, 130, 115],
        [151, 130, 115]],

       [[151, 130, 115],
        [151, 130, 115],
        [151, 130, 115],
        ...,
        [151, 130, 115],
        [151, 130, 115],
        [151, 130, 115]],

       ...,

       [[120,  94,  77],
        [120,  94,  77],
        [120,  94,  77],
        ...,
        [114,  90,  72],
        [114,  90,  72],
        [118,  94,  76]],

       [[120,  94,  77],
        [120,  94,  77],
        [120,  94,  77],
        ...,
        [110,  86,  68],
        [110,  86,  68],
        [117,  93,  75]],

       [[120,  94,  77],
        [120,  94,  77],
        [120,  94,  77],
        ...,
        [107,  83,  65],
        [107,  83,  65],
        [116,  92,  74]]

In [5]:
b,g,r = cv2.split(img)

In [15]:
b

array([[151, 151, 151, ..., 151, 151, 151],
       [151, 151, 151, ..., 151, 151, 151],
       [151, 151, 151, ..., 151, 151, 151],
       ...,
       [120, 120, 120, ..., 114, 114, 118],
       [120, 120, 120, ..., 110, 110, 117],
       [120, 120, 120, ..., 107, 107, 116]], dtype=uint8)

In [16]:
g

array([[130, 130, 130, ..., 130, 130, 130],
       [130, 130, 130, ..., 130, 130, 130],
       [130, 130, 130, ..., 130, 130, 130],
       ...,
       [ 94,  94,  94, ...,  90,  90,  94],
       [ 94,  94,  94, ...,  86,  86,  93],
       [ 94,  94,  94, ...,  83,  83,  92]], dtype=uint8)

In [17]:
r

array([[115, 115, 115, ..., 115, 115, 115],
       [115, 115, 115, ..., 115, 115, 115],
       [115, 115, 115, ..., 115, 115, 115],
       ...,
       [ 77,  77,  77, ...,  72,  72,  76],
       [ 77,  77,  77, ...,  68,  68,  75],
       [ 77,  77,  77, ...,  65,  65,  74]], dtype=uint8)

In [18]:
img.shape

(254, 198, 3)

Display each color image seperately

In [14]:
cv2.imshow('image',img)
cv2.imshow('blue',b)
cv2.imshow('green',g)
cv2.imshow('red',r)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
img_bgr=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

In [16]:
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

In [17]:
cv2.imshow('color_bgr', img)
cv2.imshow('color_rgb',img_bgr)
cv2.imshow('gray',gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
#save image 
cv2.imwrite('gray.png',gray)

True

In [20]:
cv2.imwrite('color_rgb.png',img_bgr)

True