In [1]:
import numpy as np
import cv2

In [2]:
img= cv2.imread('./faces.jpg')
cv2.imshow('face',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
face_detection_model = cv2.dnn.readNetFromCaffe('./model/deploy.prototxt.txt','./model/res10_300x300_ssd_iter_140000_fp16.caffemodel')

In [5]:
#step1- extract blob from image
blob = cv2.dnn.blobFromImage(img,1,(300,300),(104,177,123),swapRB=True)

In [6]:
#step2:set blob as inpu

face_detection_model.setInput(blob)

#step3: get the output
detection= face_detection_model.forward()

In [20]:
detection

array([[[[0.        , 1.        , 0.99828076, ..., 0.13435304,
          0.37747657, 0.6368804 ],
         [0.        , 1.        , 0.93064046, ..., 0.1735116 ,
          0.66801995, 0.6749054 ],
         [0.        , 1.        , 0.6649137 , ..., 0.14685202,
          0.9633989 , 0.5360529 ],
         ...,
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ]]]], dtype=float32)

In [7]:
detection.shape

(1, 1, 200, 7)

In [8]:
# above output meaning
# 200-> faces detection, 7: 0=image number, 1: binary(0/1), 2: confidence score(0,1)
# 3: start c, 4: start y, 5: End x, 6:end y

In [9]:
detection[0,0,:,2]

array([0.99828076, 0.93064046, 0.6649137 , 0.11303056, 0.0990653 ,
       0.09581406, 0.09539089, 0.09210994, 0.09148148, 0.09004118,
       0.08952259, 0.08925451, 0.08845698, 0.08835823, 0.08817662,
       0.08785022, 0.08761989, 0.08759253, 0.08733165, 0.08644598,
       0.08633807, 0.08580607, 0.08571839, 0.08569968, 0.08565523,
       0.08561651, 0.08543262, 0.08516434, 0.08498948, 0.0849054 ,
       0.08472105, 0.08466661, 0.08451295, 0.08432195, 0.08402866,
       0.08339363, 0.08325934, 0.08319435, 0.08300184, 0.08287057,
       0.08281695, 0.0828022 , 0.08230657, 0.0820657 , 0.08128531,
       0.08119456, 0.08109774, 0.08107881, 0.08065075, 0.08063322,
       0.08060357, 0.08035444, 0.0802448 , 0.07988586, 0.07988258,
       0.07974191, 0.07961009, 0.07956649, 0.07941596, 0.07937436,
       0.0793445 , 0.07927639, 0.07913707, 0.07913006, 0.0790798 ,
       0.07904801, 0.07900919, 0.07894584, 0.07892097, 0.07890497,
       0.07888509, 0.0788686 , 0.07882136, 0.07861339, 0.07850

In [10]:
# step4 : drawingbounding box on the top of face detection
image = img.copy()
h,w = image.shape[:2]
for i in range(0,detection.shape[2]):
    confidence = detection[0,0,i,2]
    #print(confidence)
    if confidence > 0.5:
        print(confidence)
        # diagnonal point3:7 
        box = detection[0,0,i,3:7]*np.array([w,h,w,h])
        box = box.astype('int')
        pt1 = (box[0],box[1])
        pt2 = (box[2],box[3])
        print(box)
        # draw rectangle
        cv2.rectangle(image,pt1,pt2,(0,255,0),1)

        text = 'score:{:.0f}'.format(confidence*100)
        print(text)
        cv2.putText(image,text,pt1,cv2.FONT_HERSHEY_SIMPLEX,1,(255,255,255),2)

cv2.imshow('face detection dnn',image)
cv2.waitKey(0)
cv2.destroyAllWindows()
    


0.99828076
[138  94 362 445]
score:100
0.93064046
[406 121 641 472]
score:93
0.6649137
[729 102 924 375]
score:66


In [4]:
#create face detection function

def face_detection_dnn(img):
    
    # step4 : drawingbounding box on the top of face detection
    #image = img.copy()
    h,w = image.shape[:2]
    for i in range(0,detection.shape[2]):
        confidence = detection[0,0,i,2]
        #print(confidence)
        if confidence > 0.5:
            print(confidence)
            # diagnonal point3:7 
            box = detection[0,0,i,3:7]*np.array([w,h,w,h])
            box = box.astype('int')
            pt1 = (box[0],box[1])
            pt2 = (box[2],box[3])
            print(box)
            # draw rectangle
            cv2.rectangle(image,pt1,pt2,(0,255,0),1)
    
            text = 'score:{:.0f}'.format(confidence*100)
            print(text)
            cv2.putText(image,text,pt1,cv2.FONT_HERSHEY_SIMPLEX,1,(255,255,255),2)
    return image
cv2.imshow('face detection dnn',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

NameError: name 'img' is not defined

In [5]:
cap = cv2.VideoCapture(0)
face_detection_model = cv2.dnn.readNetFromCaffe('./model/deploy.prototxt.txt',
                                                './model/res10_300x300_ssd_iter_140000_fp16.caffemodel')
while True:
    ret,frame = cap.read()
    if ret==False:
        break
    img_detection = face_detection_dnn(frame)
    cv2.imshow('real time face detection with dnn', img_detection)
    if cv2.waitKey(1) ==ord('a'):
        break

cap.release()
cv2.waitKey(0)
cv2.destroyAllWindows()


NameError: name 'image' is not defined

In [13]:
image_detect = face_detection_dnn(img)

0.99828076
[138  94 362 445]
score:100
0.93064046
[406 121 641 472]
score:93
0.6649137
[729 102 924 375]
score:66


In [14]:
cv2.imshow('face detection',image_detect)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [16]:
#real time face detection


In [6]:
cap = cv2.VideoCapture(0)
face_detection_model = cv2.dnn.readNetFromCaffe('./model/deploy.prototxt.txt',
                                                './model/res10_300x300_ssd_iter_140000_fp16.caffemodel')
while True:
    ret,frame = cap.read()
    if ret==False:
        break
    img_detection = face_detection_dnn(frame)
    cv2.imshow('real time face detection with dnn', img_detection)
    if cv2.waitKey(1) == ord('a'):
        
        break

cap.release()
cv2.waitKey(0)
cv2.destroyAllWindows()


NameError: name 'image' is not defined

In [ ]:
cv2.dnn.readNerFrom