In [1]:
import numpy as np
import cv2

In [2]:
img = cv2.imread('./m1/bird.jpg')

In [4]:
def display(winname,image):
    cv2.imshow(winname,img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    

In [5]:
display('bird',img)

In [7]:
#### image translation
tx=100
ty= 150
M= np.float32([[1,0,tx],[0,1,ty]])
M

array([[  1.,   0., 100.],
       [  0.,   1., 150.]], dtype=float32)

In [43]:
cv2.warpAffine(img,M,(img.shape[1],img.shape[0]))

array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       ...,

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [173, 124,  22],
        [250, 214, 106],
        [156, 130,  40]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [157, 108,   6],
        [255, 223, 106],
        [200, 175,  77]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [158, 111,  13],
        [248, 206,  99],
        [236, 205, 114]]

In [8]:
shifted_image = cv2.warpAffine(img,M,(img.shape[1],img.shape[0]))
cv2.imshow('shifted_image',shifted_image)
cv2.imshow('Original_image', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [9]:
def translation(image,tx,ty):
    
    M= np.float32([[1,0,tx],
             [0,1,ty]])
    shifted_img = cv2.warpAffine(image,M,(image.shape[1],image.shape[0]))
    cv2.imshow('shifted',shifted_img)
    cv2.waitKey()
    cv2.destroyAllWindows()
    

In [14]:
translation(img,0,0)

In [15]:
# rotating concept

In [16]:
img= cv2.imread('./m1/bird.jpg')

In [17]:
 display('bird',img)

In [21]:
center  = (img.shape[1]//2,img.shape[0]//2)

In [23]:
m = cv2.getRotationMatrix2D(center,45,1)

In [30]:
rotate_45 =  cv2.warpAffine(img,m,(img.shape[1],img.shape[0]))

In [32]:
display('rotate_45',rotate_45)# this may not work with latest library

In [33]:
def rotate(image,angle,scale):
    center= (image.shape[1]//2,image.shape[0]//2)
    M= cv2.getRotationMatrix2D(center,angle,scale)
    rotate_img = cv2.warpAffine(image,M,(image.shape[1],image.shape[0]))
    cv2.imshow('rotated image',rotate_img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [35]:
rotate(img,-30,1.0)

In [36]:
# resize experiment

In [37]:
img.shape

(427, 640, 3)

In [38]:
img_resize = cv2.resize(img,(300,300),interpolation=cv2.INTER_AREA)


In [40]:
display('resize',img_resize)

In [43]:
cv2.imshow('original',img)
cv2.imshow('resize',img_resize)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [42]:
img_resize = cv2.resize(img,(300,300),interpolation=cv2.INTER_AREA)

In [44]:
cv2.imshow('original',img)
cv2.imshow('resize',img_resize)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [45]:
#flipping

In [46]:
flip_img = cv2.flip(img,0)

In [47]:
cv2.imshow('original',img)
cv2.imshow('resize',flip_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [48]:
#cropping image

In [49]:
crop = img[0:100,0:100]
display('crop',crop)

In [50]:
#cv2.imshow('original',img)
cv2.imshow('resize',crop)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
translation(img,-100,-150)

'shifted_image'

array([[[ 70, 181, 219],
        [ 70, 181, 219],
        [ 70, 181, 219],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[ 69, 180, 218],
        [ 70, 181, 219],
        [ 70, 181, 219],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[ 67, 181, 218],
        [ 67, 181, 218],
        [ 67, 181, 218],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       ...,

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]]