In [1]:
import numpy as np

In [2]:
import cv2

In [3]:
img = cv2.imread('./faces.jpg')

In [4]:
img

array([[[13, 14, 12],
        [13, 14, 12],
        [14, 15, 13],
        ...,
        [ 1,  1,  1],
        [ 1,  1,  1],
        [ 1,  1,  1]],

       [[12, 13, 11],
        [12, 13, 11],
        [13, 14, 12],
        ...,
        [ 1,  1,  1],
        [ 1,  1,  1],
        [ 1,  1,  1]],

       [[13, 14, 12],
        [12, 13, 11],
        [12, 13, 11],
        ...,
        [ 2,  2,  2],
        [ 1,  1,  1],
        [ 1,  1,  1]],

       ...,

       [[14, 14, 14],
        [12, 12, 12],
        [16, 16, 16],
        ...,
        [31, 37, 44],
        [30, 36, 43],
        [40, 46, 53]],

       [[10, 11,  9],
        [ 9, 10,  8],
        [13, 14, 12],
        ...,
        [32, 38, 45],
        [32, 38, 45],
        [36, 42, 49]],

       [[ 8,  9,  7],
        [ 8,  9,  7],
        [12, 13, 11],
        ...,
        [30, 36, 43],
        [32, 38, 45],
        [31, 37, 44]]], dtype=uint8)

In [6]:
cv2.imshow('face_detection',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
img.shape

(700, 960, 3)

In [9]:
face_cascade = cv2.CascadeClassifier('./model/haarcascade_frontalface_default.xml')

In [10]:
# need conver image to gray scale to get the bounding boxes

gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

#STEP2: apply GRAY SCALE IMAGE TO CASCADE CLASSIER

boxes,detections = face_cascade.detectMultiScale2(gray)

In [12]:
boxes

array([[894, 573,  52,  52],
       [697, 107, 248, 248],
       [ 88,  75, 316, 316],
       [321,  84, 385, 385]])

In [14]:
# 4 rows detect we have 4 faces 


In [16]:
detections

array([ 4, 37, 10, 35])

In [17]:
# establish relation inside boxes and arrays 
# 4 row of boxes, 4 rows of columns = 
#1st row has 4 boxes, 
#2nd row has 37 boxes, 
#3rd row has 10 boxes
#4th row has 35 boxes


In [19]:
# correction with minimum neighbours

# need conver image to gray scale to get the bounding boxes

gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

#STEP2: apply GRAY SCALE IMAGE TO CASCADE CLASSIER

boxes,detections = face_cascade.detectMultiScale2(gray,minNeighbors=8)


In [20]:
boxes

array([[321,  84, 385, 385],
       [697, 107, 248, 248],
       [ 88,  75, 316, 316]])

In [21]:
detections

array([35, 37, 10])

In [22]:
# now reduced the boxes

In [23]:
# boxes row1  321,  84, 385, 385: x = 321, y= 84, width, height= 385

In [24]:
# draw bounding box

In [26]:
# correction with minimum neighbours
image= img.copy()
# need conver image to gray scale to get the bounding boxes

gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

#STEP2: apply GRAY SCALE IMAGE TO CASCADE CLASSIER

boxes,detections = face_cascade.detectMultiScale2(gray,minNeighbors=8)
for x,y,w,h in boxes:
    print(x,y,w,h)
    cv2.rectangle(image, (x,y),(x+w,y+h),(0,255,0,1))

cv2.imshow('face_detection', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

321 84 385 385
697 107 248 248
88 75 316 316


In [35]:
#write funcation face detection

def face_detection(img):
    image= img.copy()
    #step1: convert image to gray scale
    gray= cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    # step2: load model 
    face_cascade = cv2.CascadeClassifier('./model/haarcascade_frontalface_default.xml')
    #step2: Apply gray scale image to cascade classifier
    boxes,detections= face_cascade.detectMultiScale2(gray,minNeighbors=8)

    for x,y,w,h in boxes: 
        cv2.rectangle(image,(x,y),(x+w,y+h),(0,255,0),1)
    return image
    

In [36]:
image_detect = face_detection(image)
cv2.imshow('face_detection',image_detect)
cv2.waitKey(0)
cv2.destroyAllWindows()